version: "3.5"
services:
  phpapache:
    build:
      context: "."
      dockerfile: php.dockerfile
      args:
        uid: 1000
    container_name: phpapache
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - phpapache
  mariadb:
    image: mariadb:10.0.30
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb/dump.sql:/tmp/dump/dump.sql
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - mariadb
networks:
  backend:
    name: apachenetwork
