version: "3.5"
services:
  phpapache:
    build:
      context: "."
      dockerfile: php.dockerfile
      args:
        uid: 1000
    container_name: phpapache
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - phpapache
  pgsqldb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "dbuser"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/dump.sql:/tmp/dump/dump.sql
      - ./pgsql:/docker-entrypoint-initdb.d
    networks:
      backend:
        aliases:
          - pgsqldb
networks:
  backend:
    name: apachenetwork
